Milestone Components and Redux Store
SantiagoGuerra/magic-books pull request #3
Opened 2020-07-13 22:12 UTC by SantiagoGuerra

Hello kind reviewer, in the following list you'll find more information about the work done in this PR:

- Implemented components
- Add Store
- Use Redux State in the logic
- Initialize the state with some book
- Each book have its property, including the author property

Thanks in advance!

2020-07-13 23:01 UTC, shloch requested changes
## Hello @SantiagoGuerra 
We're good to go

Small change below, that has minor effect on your code, but just to keep up with the requirements
Please do this small change
Thanks

2020-07-13 23:01 UTC, shloch commented on src/components/BookList.js
> +import { useSelector } from 'react-redux';
this component should be in the folder : ` src/containers`
![Screen Shot 2020-07-14 at 12 03 19 AM](https://user-images.githubusercontent.com/40712459/87361712-bdcdbd00-c564-11ea-8b67-9cc06ac6ee26.png)

2020-07-13 23:01 UTC, shloch commented on src/components/BookForm.js
> +
![Screen Shot 2020-07-14 at 12 03 19 AM](https://user-images.githubusercontent.com/40712459/87361808-f077b580-c564-11ea-9eb8-5b4906590021.png)

should be in folder `/sc/containers`

2020-07-13 23:52 UTC, shloch approved these changes
![accomplished](https://user-images.githubusercontent.com/40712459/87364688-35ebb100-c56c-11ea-975b-a650b081525e.jpg)
good to go

2020-07-14 01:26 UTC, merged

2020-07-15 01:47 UTC, SantiagoGuerra commented
Hi @shloch , apparently you forgot to change the status, hehe

![Screenshot from 2020-07-14 20-44-58](https://user-images.githubusercontent.com/26417441/87493715-0a6fd180-c613-11ea-8db9-545e40619beb.png)

I'd thank you so much to help me with this, and thank you in advance again!

2020-07-15 08:52 UTC, shloch commented
Hello @santiago.....Am so sorry, must have just forgotten.....please just continue with the next milestone.....I will contact the backend team to validate manually .........

2020-07-16 08:36 UTC, shloch commented
Hello @SantiagoGuerra , you can check now, i have a confirmation that it is validated .....just hit me up on slack for confirmation
Good day

2020-07-16 18:16 UTC, SantiagoGuerra commented
@shloch I could not find you on Slack, but thank you so much for the help, the issue is solved :)

2020-07-16 22:16 UTC, shloch commented
on slack, i am <SHEY Louis CHIA>, any ways, good to know
Good day